#!/bin/bash

DOWNLOADS="$HOME/Downloads"

mkdir -p "$DOWNLOADS/text"
mkdir -p "$DOWNLOADS/docs"
mkdir -p "$DOWNLOADS/images"
mkdir -p "$DOWNLOADS/pdfs"
mkdir -p "$DOWNLOADS/videos"
mkdir -p "$DOWNLOADS/archives"
mkdir -p "$DOWNLOADS/other"

while true; do

    for file in "$DOWNLOADS"/*; do
        if [[ ! -f "$file" ]]; then
            continue
        fi

        case "$file" in
            *.txt)
                mv "$file" "$DOWNLOADS/text/"
                ;;
            *.pdf)
                mv "$file" "$DOWNLOADS/pdfs/"
                ;;
            *.jpg|*.jpeg|*.png)
                mv "$file" "$DOWNLOADS/images/"
                ;;
            *.doc|*.docx)
                mv "$file" "$DOWNLOADS/docs/"
                ;;
            *.mp4|*.mov)
                mv "$file" "$DOWNLOADS/videos/"
                ;;
            *.zip|*.tar|*.gz)
                mv "$file" "$DOWNLOADS/archives/"
                ;;
            *)
                mv "$file" "$DOWNLOADS/other/"
                ;;
        esac
    done

    sleep 2
done
